name: Build & Push Docker Image

on:
  push:
    branches:
      - "main"
      - "release/*"
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      IMAGE_NAME_LOWER: ${{ github.repository_owner }}/suse-nfs-server

    steps:
      # 🔹 Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 🔹 Enable QEMU for multi-platform support
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 🔹 Enable Docker Buildx (required for advanced builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 🔹 Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 🔹 Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 🔹 Extract Metadata (tags, labels, versions)
      - name: Extract Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            docker.io/my-docker-hub-namespace/my-docker-hub-repo
            ghcr.io/${{ env.IMAGE_NAME_LOWER }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
          labels: |
            org.opencontainers.image.title=MyNFSContainer
            org.opencontainers.image.description=A lightweight containerized NFS server for openSUSE.
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.version=${{ steps.meta.outputs.version }}
            org.opencontainers.image.licenses=MIT

      # 🔹 Build & Push Docker Image
      - name: Build and Push Docker Image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}:cache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}:cache,mode=max
          build-args: |
            GIT_COMMIT=${{ github.sha }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
          provenance: true
          sbom: true

      # 🔹 Generate Build Provenance Attestation
      - name: Generate Artifact Attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ env.IMAGE_NAME_LOWER }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
